### ISSUE TITLE
Recalculate propeller coefficients for saltwater.

### ISSUE THREAD

**Issue by arjo129** [osrf/lrauv#136]
Currently, the propeller coefficients are tuned for freshwater. With #96 we will be moving to saltwater. For the sake of consistency, we need to update the propeller coefficients.

**Comment by chapulina** [comment]
Fixed in #140. Let's close this once the documentation on how to calculate the coefficient is linked to from somewhere in this repository. I think the wiki makes sense, but I'll leave it up to @arjo129 .
