### ISSUE TITLE
DEM of Portuguese Ledge

### ISSUE THREAD

**Issue by caguero** [osrf/lrauv#146]
Create a 5x5 km Digital Elevation Model (DEM) of Portuguese Ledge in Ignition from MBARI high-precision octree maps of the area’s bathymetry.

**Comment by chapulina** [comment]
This is a work in progress. PRs and branches I'm working with:

* https://github.com/ignitionrobotics/ign-common/pull/321
* https://github.com/ignitionrobotics/ign-physics/pull/315
* https://github.com/ignitionrobotics/ign-rendering/tree/chapulina/dem
* https://github.com/ignitionrobotics/ign-gazebo/pull/1262

Notes about manipulating the raw files:

* `ign-common` is able to load NetCDF directly
* The NaN notada values are causing trouble.
    * I used QGIS's "Fill nodata" tool with 10000 px distance and was able to load the file (which ends up being GeoTIFF)
* Loading the entire DEM consumes a lot of memory, it may be more interesting to split it and use levels
* `ign-common` pads non-square DEMs so they become square, and the padding is ending up above ground for this specific file
* I haven't checked whether lat/lon look reasonable after loading the file yet
