### ISSUE TITLE
ThrusterPlugin publish angular velocity

### ISSUE THREAD

**Issue by mabelzhang** [osrf/lrauv#16]
Per https://github.com/osrf/lrauv/pull/48#pullrequestreview-698970619 and discussions there, it is helpful for users of the ThrusterPlugin to have access to the angular velocity without having to get it from the ECM. This is best obtained via the JointVelocity component as is done in https://github.com/osrf/lrauv/pull/49

This update can be started in this repo, but should then be upstreamed to ign-gazebo.

**Comment by arjo129** [comment]
See ignitionrobotics/ign-gazebo#1269
