### ISSUE TITLE
Science sensor system causes glitches in sim

### ISSUE THREAD

**Issue by braanan** [osrf/lrauv#168]
Hi @mabelzhang,

I've been testing the  empty_world env with the science sensor system in the loop and it seems like the queries are causing significant slowdowns. As a result the vehicle appears to be glitching along the navigated track. 

https://user-images.githubusercontent.com/7927479/158451273-389a4c50-e13a-4581-8a2d-d25c64254a0c.mp4

The temperature values produced for temperature seem to be correct. 

To reproduce run the lrauv-application with the following inputs:
`./bin/LRAUV -x "run Science/profile_station.xml"` 

Thanks

**Comment by mabelzhang** [comment]
Hey Ben, I was able to reproduce this on `main`.
However, when I switch to my trilinear interpolation branch in #127, the lag disappears. So, I recommend getting my PR merged so we have all the improvements.
That seems the easiest solution.

I also noticed `main` is still printing a lot of garbage from my old (3 months now) interpolation code, which has been refactored into its own class in #127 and has cleaner printouts now. Definitely a better experience.

**Comment by mabelzhang** [comment]
Quick test to switch to barycentric interpolation in #127 by this line in `ScienceSensorsSystem.cc`:
```
  this->dataPtr->interpolation.SetMethod(BARYCENTRIC);
```
Still no lag.

So I'm guess the lag might come from infrastructure.

That of course says nothing about whether interpolation is correct, which we should check separately. But seems like things are better with the new code, not worse.

**Comment by mabelzhang** [comment]
I added a few `IGN_PROFILE` lines. See timelines produced below.
You were right about the kNN search being the bottleneck. `FindTrilinearInterpolators()` takes 800 ms.
In comparison, publishing point clouds take 30 ms.

![2022-03-30-150323_3840x2160_scrot](https://user-images.githubusercontent.com/7608908/160911607-cd33c968-2152-4069-b3b9-e4e4d44866dc.png)

![2022-03-30-150421_3840x2160_scrot](https://user-images.githubusercontent.com/7608908/160911627-ed6d5960-bab7-4dd7-ab23-3831c05fa2c5.png)

![2022-03-30-150440_3840x2160_scrot](https://user-images.githubusercontent.com/7608908/160911635-6d8979a1-4d6b-4a51-9b54-73edbdaef321.png)

**Comment by braanan** [comment]
resolved in #191
