### ISSUE TITLE
[Thruster plugin] Flip sign direction.

### ISSUE THREAD

**Issue by arjo129** [osrf/lrauv#20]
Flip the sign direction of the thruster plugin/XML of joint axis to make it move forward when we give a positive thrust command.

**Comment by mabelzhang** [comment]
Has this been fixed / is the failure tracked elsewhere / can this be closed?

**Comment by chapulina** [comment]
I'm working on it as part of #48 and #37

**Comment by chapulina** [comment]
See https://github.com/osrf/lrauv/pull/76
