### ISSUE TITLE
Refactor acoustic comms

### ISSUE THREAD

**Issue by caguero** [osrf/lrauv#227]
We should use as much as we can the comms infrastructure from Gazebo and move the acoustic comms model upstream.

**Comment by adityapande-1995** [comment]
This PR adds acoustic comms upstream : https://github.com/gazebosim/gz-sim/pull/1608

**Comment by adityapande-1995** [comment]
Cherry pick the plugin and exmaple demo to garden : https://github.com/gazebosim/gz-sim/pull/1704
