### ISSUE TITLE
Ign to Gz migration

### ISSUE THREAD

**Issue by marcoag** [osrf/lrauv#234]
Work towards https://github.com/osrf/lrauv/issues/225.

We should apply the necessary changes to cope with the migration from Ign to Gz.

Here is a list of places to look for possible updates:

- [x] [OSRF lrauv repository ](https://github.com/osrf/lrauv/pull/237).
- [x] MBARI software control code.
- [x] Dockers and docker hub urls.
- [x] Documentation: Wiki and [Readme](https://github.com/osrf/lrauv/pull/246).
  - Review wiki for MBARI side changes.

**Comment by hidmic** [comment]
Migration completed a while back.
