### ISSUE TITLE
How to modify Portuguese ledge world file? 

### ISSUE THREAD

**Issue by gnanukoth** [osrf/lrauv#284]
Hello, our team is currently trying to simulate some scenarios for the lrauv to work in. We would like to add a docking station and simulate the vehicle coming to a stop when it reaches the docking station. We are unable to add any models to the world using the gui nor make changes in the world file. Can you guide us in this regards? Thank you!

**Comment by arjo129** [comment]
I recommend directly editing the SDF file here: https://github.com/osrf/lrauv/blob/main/lrauv_gazebo_plugins/worlds/empty_environment.sdf

This project does not support world editing. PRs are however welcome upstream in [gazebo](https://github.com/gazebosim/).
