### ISSUE TITLE
Automated mission tests do not return clean command prompt

### ISSUE THREAD

**Issue by mabelzhang** [osrf/lrauv#39]
## Unexpected behavior
As discussed in https://github.com/osrf/lrauv/pull/82#issuecomment-910381371 , automated mission tests added in osrf/lrauv#82 would finish running, return the command prompt, but nothing typed at the prompt would be visible.
The typed content is there – if you hit enter, the typed stuff would get executed. It just doesn't show up.

User must type `reset` to get keyboard input to show up again.

## Measurement of success
The following tests return clean prompt on termination:
```
build/lrauv_ignition_plugins/test_mission_pitch_mass 
build/lrauv_ignition_plugins/test_mission_depth_vbs
build/lrauv_ignition_plugins/test_mission_yoyo_circle
```

**Comment by hidmic** [comment]
This is no longer a problem. In any case, mission tests no longer live in this repository.
