### ISSUE TITLE
Mass shifter test failing

### ISSUE THREAD

**Issue by mabelzhang** [osrf/lrauv#40]
There's a (new?) runtime error if I run the mass shifter test:
```
$ build/lrauv_ignition_plugins/test_mass_shifter  
...
[Err] [JointPositionController.cc:256] [JointPositionController]: Detected an invalid <joint_index> parameter. The index specified is [0] but the joint only has [0] index[es]. This controller will be ignored
[Err] [JointPositionPlugin.cc:164] Joint [battery_joint] unable to get position
...
```

This might be from the latest Ignition Fortress release?
For some reason it thinks `battery_joint` has 0 indices?

That test almost always fails on my local machine.

@arjo129 @chapulina clues?

**Comment by mabelzhang** [comment]
Has this been fixed / is the failure tracked elsewhere / can this be closed?

**Comment by chapulina** [comment]
The test has been passing (at least since 2b07660710f29e71e790e2b2f5fd14f03cddb671), and the warning is gone since https://github.com/ignitionrobotics/ign-gazebo/pull/1098.

Closing :+1:
