### ISSUE TITLE
Investigate weird oscillation in main

### ISSUE THREAD

**Issue by arjo129** [osrf/lrauv#49]

**Comment by braanan** [comment]
@chapulina @arjo129 Does this jittery oscillation also happen at depth or is it just on the surface? Is the buoyancy plugin accounting for partially submerged volumes etc? Thanks

**Comment by chapulina** [comment]
> Does this jittery oscillation also happen at depth or is it just on the surface? Is the buoyancy plugin accounting for partially submerged volumes etc?

We have uniform buoyancy everywhere right now, no distinction between water and air until #38 is addressed. So the depth shouldn't make a difference here.
